#!/usr/bin/env node

/**
 * SentinelAI API Key Diagnostics & Testing Tool
 * 
 * This CLI utility helps developers audit, diagnose, and test any 
 * Sentinel API Key generated by the pay-per-use marketplace. It verifies:
 * 1. Database presence and state of the key.
 * 2. Status of the associated AI Service.
 * 3. Upstream AI provider connectivity and authentication.
 * 
 * Usage:
 *   node verify-key.js [YOUR_API_KEY]
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import readline from "readline";
import { AccessToken } from "./src/models/AccessToken.js";
import { Service } from "./src/models/Service.js";
import { forwardChatCompletion } from "./src/services/aiProxy.js";
import { decryptSecret } from "./src/utils/encrypt.js";

// Load environment variables
dotenv.config();

// ANSI Colors for premium CLI styling
const colors = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  dim: "\x1b[2m",
  underscore: "\x1b[4m",
  fgGreen: "\x1b[32m",
  fgRed: "\x1b[31m",
  fgYellow: "\x1b[33m",
  fgBlue: "\x1b[34m",
  fgMagenta: "\x1b[35m",
  fgCyan: "\x1b[36m",
  bgBlack: "\x1b[40m",
  bgCyan: "\x1b[46m"
};

/**
 * Renders a stylized banner
 */
function renderBanner() {
  console.log(`\n${colors.fgCyan}${colors.bright}====================================================`);
  console.log(`🛡️  SENTINEL-AI KEY DIAGNOSTICS & VERIFICATION TOOL`);
  console.log(`====================================================${colors.reset}\n`);
}

/**
 * Prompts user for input when API key isn't passed as CLI parameter
 */
function promptUser(query) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  return new Promise((resolve) => rl.question(query, (ans) => {
    rl.close();
    resolve(ans.trim());
  }));
}

/**
 * Formats keys or addresses safely
 */
function maskString(str, visibleCount = 12) {
  if (!str || str.length <= visibleCount * 2) return str;
  return `${str.slice(0, visibleCount)}...${str.slice(-visibleCount)}`;
}

/**
 * Main check logic
 */
async function main() {
  renderBanner();

  let apiKey = process.argv[2]?.trim();

  if (!apiKey) {
    console.log(`${colors.fgYellow}💡 Hint: You can pass the API key directly: node verify-key.js <api-key>${colors.reset}`);
    apiKey = await promptUser(`${colors.bright}Enter the Sentinel API key to test: ${colors.reset}`);
  }

  if (!apiKey) {
    console.log(`\n${colors.fgRed}❌ Error: No API key was provided.${colors.reset}\n`);
    process.exit(1);
  }

  if (!apiKey.startsWith("sk-sentinel-")) {
    console.log(`\n${colors.fgYellow}⚠️  Warning: API Key does not start with standard "sk-sentinel-" prefix. Proceeding anyway...${colors.reset}\n`);
  }

  if (!process.env.MONGO_URI) {
    console.log(`${colors.fgRed}❌ Error: MONGO_URI is missing in your backend/.env file.${colors.reset}\n`);
    process.exit(1);
  }

  console.log(`${colors.fgCyan}🔌 Connecting to MongoDB...${colors.reset}`);
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log(`${colors.fgGreen}✅ Connected to database successfully.${colors.reset}\n`);
  } catch (err) {
    console.error(`${colors.fgRed}❌ Database connection failed:${colors.reset}`, err.message);
    process.exit(1);
  }

  try {
    console.log(`${colors.bright}🔎 Phase 1: Database Token Lookup...${colors.reset}`);
    const tokenDoc = await AccessToken.findOne({ key: apiKey });

    if (!tokenDoc) {
      console.log(`\n${colors.fgRed}❌ Diagnostic Failed: Key was not found in the database.${colors.reset}`);
      console.log(`${colors.dim}Suggestions: Check if the key belongs to the current database environment.${colors.reset}\n`);
      return;
    }

    console.log(`  └─ Status: ${colors.fgGreen}FOUND${colors.reset}`);
    console.log(`  └─ Token ID: ${colors.dim}${tokenDoc._id}${colors.reset}`);
    console.log(`  └─ User Wallet: ${colors.fgBlue}${tokenDoc.userWallet}${colors.reset}`);
    console.log(`  └─ Date Created: ${new Date(tokenDoc.createdAt).toLocaleString()}`);
    console.log(`  └─ Token Used State: ${tokenDoc.isUsed ? `${colors.fgRed}Yes (Consumed)${colors.reset}` : `${colors.fgGreen}No (Unused)${colors.reset}`}\n`);

    console.log(`${colors.bright}🔎 Phase 2: Associated Service Verification...${colors.reset}`);
    const service = await Service.findById(tokenDoc.serviceId);

    if (!service) {
      console.log(`\n${colors.fgRed}❌ Diagnostic Failed: The AI Service attached to this token (ID: ${tokenDoc.serviceId}) no longer exists.${colors.reset}\n`);
      return;
    }

    console.log(`  └─ Service ID: ${colors.dim}${service._id}${colors.reset}`);
    console.log(`  └─ Service Name: ${colors.fgCyan}${service.name || "Unnamed Service"}${colors.reset}`);
    console.log(`  └─ Creator Wallet: ${colors.fgBlue}${service.creatorWallet}${colors.reset}`);
    console.log(`  └─ Sentinel Official: ${service.isSentinalOfficial ? `${colors.fgGreen}Yes (Sentinel)${colors.reset}` : "No"}`);
    console.log(`  └─ State: ${service.isPaused ? `${colors.fgRed}Paused (Service Suspended)${colors.reset}` : `${colors.fgGreen}Active (Live)${colors.reset}`}`);
    console.log(`  └─ AI Provider: ${colors.fgMagenta}${service.aiProvider || "None"}${colors.reset}`);
    console.log(`  └─ Model Name: ${colors.fgMagenta}${service.modelName || "Default"}${colors.reset}`);
    console.log(`  └─ Decryption Status: ${service.encryptedApiKey ? `${colors.fgGreen}Encrypted Key Present${colors.reset}` : `${colors.fgRed}Key Missing${colors.reset}`}\n`);

    if (service.isPaused) {
      console.log(`${colors.fgYellow}⚠️  Warning: Service is paused. Upstream AI proxy requests will be rejected by default.${colors.reset}\n`);
    }

    if (!service.encryptedApiKey) {
      console.log(`${colors.fgRed}❌ Diagnostic Failed: Service lacks an encrypted provider API key.${colors.reset}\n`);
      return;
    }

    console.log(`${colors.bright}🔎 Phase 3: Upstream AI Integration & Credential Decryption...${colors.reset}`);
    let providerKey;
    try {
      providerKey = decryptSecret(service.encryptedApiKey);
      console.log(`  └─ Credential Decryption: ${colors.fgGreen}SUCCESS${colors.reset} (${maskString(providerKey, 4)})`);
    } catch (e) {
      console.log(`\n${colors.fgRed}❌ Diagnostic Failed: Key decryption failed. Make sure ENCRYPTION_KEY in .env matches the key used to encrypt it.${colors.reset}\n`);
      return;
    }

    console.log(`\n${colors.fgCyan}🚀 Phase 4: Triggering Live Upstream Connectivity Test...${colors.reset}`);
    const testBody = {
      messages: [{ role: "user", content: "Respond with: Connectivity verified successfully!" }],
      max_tokens: 30
    };

    const startTime = Date.now();
    const response = await forwardChatCompletion({
      provider: service.aiProvider,
      apiKey: providerKey,
      model: service.modelName,
      body: testBody,
      customEndpointUrl: service.customEndpointUrl || ""
    });
    const durationMs = Date.now() - startTime;

    console.log(`  └─ Connectivity Status: ${colors.fgGreen}SUCCESS${colors.reset}`);
    console.log(`  └─ Response Latency: ${colors.fgYellow}${durationMs}ms${colors.reset}`);
    
    const responseText = response?.choices?.[0]?.message?.content || JSON.stringify(response);
    console.log(`  └─ AI Provider Response: "${colors.bright}${colors.fgGreen}${responseText.trim()}${colors.reset}"\n`);

    console.log(`${colors.bgCyan}${colors.fgBlack}${colors.bright}  🎉 DIAGNOSTIC COMPLETED: ALL AUDIT PHASES PASSED SUCCESSFULLY!  ${colors.reset}\n`);

  } catch (err) {
    console.log(`\n${colors.fgRed}❌ Diagnostic Failed!${colors.reset}`);
    if (err.response) {
      console.error(`  └─ Upstream API Status Code: ${colors.fgYellow}${err.response.status}${colors.reset}`);
      console.error(`  └─ Upstream Error Response:`, JSON.stringify(err.response.data));
    } else {
      console.error(`  └─ Error Detail:`, err.message || err);
    }
    console.log();
  } finally {
    await mongoose.disconnect();
    console.log(`${colors.dim}Disconnected from database.${colors.reset}\n`);
  }
}

main();
